dataset_root: data/raw/UAV123
processed_root: data/processed

template_size: 127
search_size: 255

batch_size: 8
epochs: 10
learning_rate: 0.0001
backbone_learning_rate: 0.00001
weight_decay: 0.0001

freeze_backbone: false
unfreeze_last_n_backbone_blocks: 0
device: cuda

checkpoint_dir: /kaggle/working/checkpoints
log_dir: /kaggle/working/logs

backbone_variant: small
feature_channels: 96
pretrained_backbone: true
normalize_input: true

cls_weight: 1.0
reg_weight: 5.0
smooth_l1_beta: 1.0

num_workers: 2
pin_memory: true

train_samples_per_epoch: 512
val_samples_per_epoch: 128